apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        name: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.gcloud.region }}-docker.pkg.dev/{{ .Values.gcloud.projectId }}/helloworld/{{ .Values.name }}:{{ .Values.image.version }}"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.port }}"
            - name: SECURITY_ISSUER_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: keycloakconfigmap
                  key: realmurl
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongosecret
                  key: url
            - name: TRACING_PROBABILITY
              value: "{{ .Values.tracing.probability }}"
            - name: ZIPKIN_HOSTNAME
              value: "{{ .Values.tracing.zipkin.serviceName }}.{{ .Values.shared.namespace }}.svc.cluster.local"
            - name: GCLOUD_PROJECT_ID
              value: "{{ .Values.gcloud.projectId }}"
            - name: GCLOUD_PUBSUB_SUBSCRIPTION_ID_MERCHANT
              value: "{{ .Values.gcloud.pubsub.subscriptionId.merchant }}"
            - name: ENV_ID
              value: "{{ .Values.env.id }}"