apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.name }}
  endpoints:
    - port: 8080
      path: /actuator/prometheus
      interval: 30s
# Require: Managed Service for Prometheus	Enabled