apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        name: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: STORAGE_TYPE
              value: stackdriver
            - name: STACKDRIVER_PROJECT_ID
              value: "{{ .Values.gcloud.projectId }}"