apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: "lb-{{ .Values.name }}"
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.port }}
        requestPath: /actuator/health
  targetRef:
    group: ""
    kind: Service
    name: {{ .Values.name }}