apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
spec:
  parentRefs:
    - name: {{ .Values.shared.gateway.name }}
      namespace: {{ .Values.shared.namespace }}
  rules:
    - backendRefs:
        - name: {{ .Values.name }}
          port: {{ .Values.port }}
      matches:
        - path:
            type: PathPrefix
            value: "/{{ .Values.env.id }}/merchant"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /